### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cortner** [cortner/Isaac.jl#3]
* [ ] Register the repository
* [ ] combine `dlanczos`, `dgmres` and `darnoldi` into a single code 
* [ ] combine `nsoli, nsolimod` and `nsolistab`
* [X] generalise `nsolimod` to stable equilibria of nonlinear systems (cf string method)
* [ ] fully generalise `nsolimod` to nonlinear systems
* [ ] improve linesearch
* [ ] Performance tuning
* [ ] current implementation of `dlanzcos` is very naive as it does not exploit the usual structures in Lanczos iterations; this should eventually be fixed or maybe just move to Arnoldi, and never worry about Lanczos
* [ ] integrate with `Optim.jl`, `NLsolve.jl`, `NLSolversBase.jl`
* [ ] generalise codes to admit actual hessian-vector products and full hessian inversion, depending on whether the objective is `OnceDifferentiable` or `TwiceDifferentiable`
* [ ] add more examples
* [ ] benchmark `nkminim` against `Optim.jl` and against `NLopt.jl`
